name: AmongUsMode 
author: Charly 
version: 1.0 
main: fr.charly.amongusmode.Main
<<<<<<< HEAD
=======
author: Charly #Auteur du plugin
version: 1.0 #Version du plugin
dependecies: #de quel plugin il dependra, dans notre cas, nous n'allons utiliser aucun autre plugin...
api-version: 1.8 #Version sur laquelle le plugin fonctionnera
>>>>>>> branch 'master' of https://github.com/baba72210/AmongUsMode.git
commands: 
  test:
    description: ceci est un test
    permission: test.use