name: AmongUsMode #nom du plugin
main: Main
author: Charly #Auteur du plugin
version: 1.0 #Version du plugin
dependecies: #de quel plugin il dépendra, dans notre cas, nous n'allons utiliser aucun autre plugin...
api-version: 1.8 #Version sur laquelle le plugin fonctionnera
commands: #les commandes
  manger: #la commande manger, ne mettez pas de tabulation, mais 2 espaces
    permission: manger.use #la permission
    description: Te permet de manger de la nourriture facilement #la description qui s'affiche lorsqu'on fait /help