name: AmongUsMode 
main: fr.charly.amongusmode.Main
author: Charly #Auteur du plugin
version: 1.0 #Version du plugin
dependecies: #de quel plugin il dependra, dans notre cas, nous n'allons utiliser aucun autre plugin...
commands: 
  test:
    description: ceci est un test
    permission: test.use   
  impostor:
    description: Clear puis give dans l inventaire l epee de l impostor
    permission: imp.use
  teamSet:
     description: random teaming
     permission: teamSet.use
  teamCheck:
     description: check if in onlineteam
     permission: teamCheck.use
