name: AmongUsMode 
author: Charly 
version: 1.0 
main: fr.charly.amongusmode.Main
author: Charly #Auteur du plugin
version: 1.0 #Version du plugin
dependecies: #de quel plugin il dependra, dans notre cas, nous n'allons utiliser aucun autre plugin...
commands: 
  test:
    description: ceci est un test
    permission: test.use